### ISSUE TITLE
在cls文件制作封面开头加一个全角空格，可以解决winfonts下编译后生成pdf复制乱码的问题

### ISSUE THREAD

**Issue by Wenhao-Xu** [xen0n/JNUthesis#18]
但是封面内容会往下去一点，如图
![pdf](https://user-images.githubusercontent.com/34877512/53644992-df315000-3c72-11e9-8ee5-de73e4c4616f.png)

**Comment by xen0n** [comment]
卧槽，666，刚看到

回头试一试。。。

**Comment by Wenhao-Xu** [comment]
测试了下，一级居中大标题还是乱码

**Comment by Wenhao-Xu** [comment]
感觉adobefonts显示效果除了标点，不同外，其余都类似，倒是不会产生乱码

**Comment by xen0n** [comment]
> 测试了下，一级居中大标题还是乱码

想起来了，这个貌似是因为 Windows 宋体（SimSun）（忘了 SimHei 是不是也这样）的 CMap 数据有问题，貌似到现在也没有解决方案= = 应该也是我当时不推荐使用 winfonts 给查重系统编译的原因

**Comment by Wenhao-Xu** [comment]
我试了下adobefonts，貌似不会出现乱码的情况了。跟windows宋体看起来差不多，但总感觉好像淡了点儿

**Comment by mchen19** [comment]
TeXLive2019下 (好像)正常了

**Comment by xen0n** [comment]
wdnmd 2019都出了

今晚回家试试

**Comment by aaa1999** [comment]
> wdnmd 2019都出了
> 
> 今晚回家试试

老哥，现在windows平台能用了吗。

**Comment by Wenhao-Xu** [comment]
windows一直能用啊  我当时就是windows的

**Comment by xen0n** [comment]
是吗 我自己 TeX 环境换了电脑都没了 如果有人能报现在 `winfonts` 没有复制乱码问题的话我就能把这 issue close 了

**Comment by aaa1999** [comment]
> windows一直能用啊 我当时就是windows的

我这就克隆的仓库，texlive2021,texstudio,win10 xeletex
然后现在报这个问题。不知道老哥怎么解决的。
![image](https://user-images.githubusercontent.com/49224989/169639599-8300e093-3796-45ed-8208-ea984c8d6323.png)
没有找到解决的办法。

**Comment by xen0n** [comment]
> > windows一直能用啊 我当时就是windows的
> 
> 我这就克隆的仓库，texlive2021,texstudio,win10 xeletex 然后现在报这个问题。不知道老哥怎么解决的。 ![image](https://user-images.githubusercontent.com/49224989/169639599-8300e093-3796-45ed-8208-ea984c8d6323.png) 没有找到解决的办法。

字体没加载成功，我是 Linux 环境，当然这个讨论偏题了，想了想我还是先 close 了，建个新 issue
