### ISSUE TITLE
参考文献问题

### ISSUE THREAD

**Issue by ghost** [xen0n/JNUthesis#23]
我的博士论文是LaTeX，但是毕业论文的模板是我自己写的，我知道这其中的工作量，所以很感谢作者的付出，真的谢谢。我看了cls文件，作者的水平真的很高，很膜拜。一个小问题：参考文献为什么是左对齐，而不是是两端对齐？我查了cls文件，不明白从哪里可以修改。还有，正规的出版行业没有用宋体加黑表示强调的，这是模板本身的问题，作者可以在latex中直接将宋体加黑改成黑体算了。我是江南大学的老师，邮件是xfji at 163 dot com  欢迎交流。

**Comment by ghost** [comment]
还有，个人感觉这个模板根本不需要那么多的宏包，其实很多宏包根本用不到，可以删去的。还有，硕士论文和博士论文的封面，江南大学的logo和下面一行“硕士（博士）学位论文”之间可以空一些，一点不空的话，难看得很。

**Comment by xen0n** [comment]
> 作者的水平真的很高

基本上 99% 的代码都是 fork 的 ;-)

> 参考文献为什么是左对齐，而不是是两端对齐？

我记得当时应该是编译自己的学位论文，发现两端对齐的个别行字数极少，可能是我引用了网络文献，URL 很长，影响了折行的缘故。于是改掉了。

> 我查了cls文件，不明白从哪里可以修改。

直接改 dtx 文件重新编译；具体我应该拆了提交，相关的提交 revert 掉，重编译应该就好了。

> 正规的出版行业没有用宋体加黑表示强调的，这是模板本身的问题，作者可以在latex中直接将宋体加黑改成黑体算了。

我在江南大学的 7 年间，我和我小伙伴的学院一直是禁用任何中易宋体与 Times New Roman 之外任何其他字体的。这个是不得已而为之 🌚

**Comment by ghost** [comment]
能否把最新的cls文件发给我一下？xfji at 163 dot com

**Comment by ghost** [comment]
我2006年写过我自己博士论文的模板，当时处理换行的论文标题时候，用的不是titlea和titleb这种形式，而是直接采用了表格，在题目中用\换行，这样如果出现\，就相当于表格有两行，如果没有，就是一行。

**Comment by xen0n** [comment]
最新的 cls 就是项目里自带的那个；很久没空维护这个库了。

**Comment by ghost** [comment]
好的，谢谢~
