### ISSUE TITLE
虽然看起来非常nice！但真的。。。折腾了两天了还能编译过去

### ISSUE THREAD

**Issue by thfylsty** [xen0n/JNUthesis#24]
是不是TeXLive2019不支持的呀，我正在下载2018试试

TexStdio也各种报错emmmm要死了

看见前面有大佬用CTex，我试了下也不行

**Comment by thfylsty** [comment]
emm

**Comment by xen0n** [comment]
啊，实在抱歉，这个包很久没维护了，当时不是很懂TeX这种东西如何做CI，我的伙伴们都已经毕业很多年了。。。

**Comment by Wenhao-Xu** [comment]
要不下低点的版本？我当时是TeXLive2017，其他是texstudio（应该版本也不是很新）、xeletex，操作系统win10。当时还装了CTeX，发现跑的时候命令会冲突，后来studio里自行设置了下xelatex命令的指向路径（好像指向了软件自己的xeletex.exe）

**Comment by xen0n** [comment]
坟贴。。虽然很想帮忙，但现在别的高优先级事情实在是太多了 :facepalm:

closing...
