### ISSUE TITLE
学士学位论文排版问题

### ISSUE THREAD

**Issue by xen0n** [xen0n/JNUthesis#4]
* 封面页
    * [x] ~~小初号看上去有点大~~ 无关紧要，排出来被拒了再说
    * [x] 标题左对齐
    * [x] 第二行指导教师
* 中文摘要页
    * [x] 标题是宋体“摘（全角空格）要”
    * [x] 页眉是“摘要”
* 英文摘要页
    * [x] 标题是ABSTRACT
    * [x] 页眉是Abstract
    * [x] 不分两页
* 目录页
    * [x] 标题是“目（全角空格）录”
    * [x] 页眉是“目录”
    * [x] 字号
    * [x] 间距
    * [x] 缩进
    * [x] 章节号是“第（阿拉伯数字）章”
    * [x] 参考文献要进目录
* 正文
    * [x] 章节号是“第（阿拉伯数字）章”
* 其他
    * [x] 相关资料封面页

**Comment by tvytlx** [comment]
摘要页不分两页的问题，我把[L3570](https://github.com/xen0n/JNUthesis/blob/develop/jnuthesis.dtx#L3570), [L3522](https://github.com/xen0n/JNUthesis/blob/develop/jnuthesis.dtx#L3522)改成了`\clearpage`，最后结果是，中文摘要页后面空白页没了，英文摘要页后面依然插入了一页空白。? . ?

**Comment by xen0n** [comment]
我自己改。。。参考一下这个地方之前1.x版本是怎么解决的。我在改硕士学位论文的格式

**Comment by tvytlx** [comment]
对了，我们老师这次发的模板，我发你邮箱吧。

**Comment by xen0n** [comment]
可以可以～

**Comment by xen0n** [comment]
i@xen0n.name

**Comment by xen0n** [comment]
跟我们当年一样，目录格式好像还是错的，不知道是不是改了

**Comment by tvytlx** [comment]
目录页的页脚的数字类型好像不一样了

**Comment by xen0n** [comment]
小写罗马数字啊，一直都是

**Comment by tvytlx** [comment]
好吧，我对比的是你reference文件夹里的学士论文模板。= =

反正现在正确结果应该是目录页独立编号，然后页脚小写罗马数字对吧~

**Comment by tvytlx** [comment]
https://github.com/xen0n/JNUthesis/blob/develop/bachelor.tex#L1173

这个似乎得改成bachelor了？

**Comment by xen0n** [comment]
哦，那个学位论文模板是硕士的 😂😂😂

嗯，那个地方确实要改掉。马上 push 一个

**Comment by xen0n** [comment]
还有那个目录里头所有文字都是小五号这个你问下你老师，显然是错的，正常应该跟后边点线和页码的字号一样，现在这样奇丑无比也不知道谁改的

**Comment by xen0n** [comment]
咦，不对了，我14年拿到的模板目录页格式也错了，你看到的目录页格式是什么样的，我在Linux WPS Office下看到的是这样的

![screen](https://cloud.githubusercontent.com/assets/1175567/23821088/a8803112-0663-11e7-8eb5-5c071d501c46.png)

**Comment by tvytlx** [comment]
有区分，我是 Mac下的Microsoft office 2011
![image](https://cloud.githubusercontent.com/assets/7189225/23821096/b8f49f1a-0663-11e7-9ca7-0bfc1cd13859.png)

**Comment by xen0n** [comment]
你这个渲染是对的。

那你们的格式要求跟我们当时一点都没变化，模板上连示例姓名和导师名字都一样 233

**Comment by tvytlx** [comment]
那就好，交给你了。(我好像改不来了 OTL)

对了，`编号`的位置，我用目测觉得27em好像远了点，准确值大概在(26,27)区间内？下面是26em编译的结果和实际的结果
![image](https://cloud.githubusercontent.com/assets/7189225/23821126/526114f8-0664-11e7-9bca-1ea1521f101f.png)

![image](https://cloud.githubusercontent.com/assets/7189225/23821176/6ff3d43c-0665-11e7-8b38-c5f06820be56.png)

**Comment by xen0n** [comment]
那个我随便写的233 不用在意

**Comment by xen0n** [comment]
@arctanx0 摘要页不分两张纸的问题已经解决，只有中文封面页后面的`\cleardoublepage`要换，英文那个不用换。

**Comment by tvytlx** [comment]
恩 摘要页后面的空白页没了，但是中文封面页后面有一页空白。

![image](https://cloud.githubusercontent.com/assets/7189225/23821692/ae833570-0675-11e7-9acb-659c43afbfca.png)

**Comment by xen0n** [comment]
那个是应该有的，直接双面打印封面页就是一张单面的纸

**Comment by xen0n** [comment]
全部完成，closing
