### ISSUE TITLE
Smaller MacTeX jnuname.eps加载失败

### ISSUE THREAD

**Issue by xen0n** [xen0n/JNUthesis#6]
cc #5

**Comment by tvytlx** [comment]
应该是smaller版本包没装全(可能编译的时候有Warning，被我忽视了吧)，装full `MacTeX`高枕无忧。。

![image](https://cloud.githubusercontent.com/assets/7189225/23732007/9d91597a-04ab-11e7-9e0b-28770b1802c3.png)

**Comment by xen0n** [comment]
好。。。可以更新文档了

closing
