### ISSUE TITLE
论文中出现的间距问题

### ISSUE THREAD

**Issue by tvytlx** [xen0n/JNUthesis#9]
对比了一下学校模板，然后有这些问题需要讨论。cc @xen0n @codefalling

距离左边七个英文空格
![image](https://cloud.githubusercontent.com/assets/7189225/26292127/0f362c6c-3ee6-11e7-9825-ce055b496c93.png)

大概要缩一半？（目前摘要页看起来是正确的，不知道正文里是否是有意为之）
![image](https://cloud.githubusercontent.com/assets/7189225/26292166/4424ac14-3ee6-11e7-88a6-18ffce7c70b3.png)

加一个英文空格（目前没有空格）
![image](https://cloud.githubusercontent.com/assets/7189225/26292167/469c4844-3ee6-11e7-8279-dbf4350bf71f.png)

**Comment by xen0n** [comment]
第一个问题，我的本科毕业论文封面此处就是图中的间距设置，通过了

**Comment by xen0n** [comment]
另：标题两行左边其实有2个半角空格，这个顶格的话老师有没有说什么

**Comment by xen0n** [comment]
第二个问题，我的模板图表编号与名称之间是一个半角空格无误

**Comment by tvytlx** [comment]
#8 这个 PR 看起来没有解决正文页面顶部间距过大的问题？

**Comment by xen0n** [comment]
第一个、第二个解决
第三个不知道是不是仅有理学院才存在该问题

**Comment by tvytlx** [comment]
第三个没有问题，顺利毕业了。close
